spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/map_community
    username: root
    password: 0917
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: H2
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.MYSQL5InnoDBDialect
        query.in_clause_parameter_padding: true

    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
