server:
  port: 8080
  servlet:
    context-path: /mapcommu
    encoding:
      charset: UTF-8
      enabled: true
      force: true
jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
spring:
  security:
    enabled: false

